# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# fonts
font_family             JetBrains Mono Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               20.0

# cursor
cursor_shape            block
cursor_blink_interval   5

# scroll
scrollback_lines        100000

# input
input_delay             1
repaint_delay           5

# window size
remember_window_size    yes
initial_window_width    1280
initial_window_height   1080

# terminal ui
term                    xterm-256color

# window layout
tab_bar_style powerline
tab_powerline_style angled
tab_title_template "{num_windows} {tab.active_wd}"

### remap kitty to use ⌥ and ⌘:
map cmd+v paste_from_clipboard
## jump to end of line:
map super+right send_text all \x05
## jump to start of line:
map super+left send_text all \x01
## jump right to end of word:
map alt+right send_text all \x1b\x66
## jump left to beginning of word:
map alt+left send_text all \x1b\x62
## delete line from cursor position to start of line:
map super+backspace send_text all \x15
## delete word works by default via opt+backspace
## undo:
map super+z send_text all \x1f

action_alias launch_tab launch --cwd=current --type=tab

map cmd+alt+t launch_tab nvim .
map cmd+t launch_tab
map ctrl+shift+enter launch --cwd=current --type=window
