#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=30 blur_radius=30 color=0x00ffffff

##### Defaults #####
default=(
  padding_left=3
  padding_right=3
  icon.font="JetBrainsMono Nerd Font:Bold:13.0"
  label.font="JetBrainsMono Nerd Font:Bold:13.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/chevron.sh
source $ITEM_DIR/front_app.sh

##### Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
