return {
	-- "stevearc/conform.nvim",
	-- lazy = false,
	-- optional = false,
	-- event = { "BufReadPre", "BufNewFile", "BufWritePre" },
	-- cmd = { "ConformInfo" },
	-- keys = {
	-- 	-- taken from https://github.com/stevearc/conform.nvim/issues/192#issuecomment-2573170631
	-- 	{
	-- 		"<leader>tf",
	-- 		function()
	-- 			-- If autoformat is currently disabled for this buffer,
	-- 			-- then enable it, otherwise disable it
	-- 			if vim.b.disable_autoformat then
	-- 				vim.cmd("FormatEnable")
	-- 				vim.notify("Enabled autoformat for current buffer")
	-- 			else
	-- 				vim.cmd("FormatDisable!")
	-- 				vim.notify("Disabled autoformat for current buffer")
	-- 			end
	-- 		end,
	-- 		desc = "Toggle autoformat for current buffer",
	-- 	},
	-- },
	-- opts = function()
	-- 	local opts = {
	-- 		formatters_by_ft = {
	-- 			docker = { "dockerfile-language-server, docker-compose-language-server" },
	-- 			hcl = { "hcl" },
	-- 			json = { "prettierd", "jq", stop_after_first = true },
	-- 			lua = { "stylua" },
	-- 			markdown = { "markdownlint-cli2" },
	-- 			python = {
	-- 				-- To fix auto-fixable lint errors.
	-- 				"ruff_fix",
	-- 				-- To run the Ruff formatter.
	-- 				"ruff_format",
	-- 				-- To organize the imports.
	-- 				"ruff_organize_imports",
	-- 			},
	-- 			shell = { "shfmt" },
	-- 			sql = { "sqlfmt" },
	-- 			terraform = { "terraform_fmt" },
	-- 		},
	-- 		default_format_opts = {
	-- 			timeout_ms = 2500,
	-- 			lsp_format = "fallback",
	-- 			async = false,
	-- 			quiet = false,
	-- 		},
	-- 	}
	--
	-- 	vim.api.nvim_create_user_command("FormatEnable", function()
	-- 		vim.b.disable_autoformat = false
	-- 		vim.g.disable_autoformat = false
	-- 	end, {
	-- 		desc = "Re-enable autoformat-on-save",
	-- 	})
	-- 	return opts
	-- end,
}
