return {
    "folke/snacks.nvim",
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    lazy = true,
    opts = {
        animate = { enabled = false },
        bigfile = { enabled = false },
        dashboard = { enabled = false },
        debug = { enabled = false },
        dim = { enabled = false },
        explorer = { enabled = false },
        git = { enabled = false },
        gitbrowse = { enabled = false },
        image = { enabled = false },
        indent = { enabled = false },
        input = { enabled = false },
        layout = { enabled = false },
        notifier = { enabled = false },
        notify = { enabled = false },
        picker = { enabled = false },
        profiler = { enabled = false },
        quickfile = { enabled = false },
        rename = { enabled = false },
        scope = { enabled = false },
        scratch = { enabled = false },
        scroll = { enabled = false },
        statuscolumn = { enabled = false },
        terminal = { enabled = false },
        toggle = { enabled = false },
        util = { enabled = false },
        win = { enabled = false },
        words = { enabled = false },
        zen = { enabled = false },

        bufdelete = { enabled = true },
        lazygit = { enabled = true },
    },
    keys = {
        { "<leader>lg", function() Snacks.lazygit.open(opts) end, desc = "LazyGit (snacks)" },
        { "<leader>bd", function() Snacks.bufdelete() end,        desc = "Delete buffer (snacks)" },
    }
}
