return {
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "aadv1k/gdoc.vim", enabled = false },
	{ "kristijanhusak/vim-dadbod-completion", enabled = false },
	{ "kristijanhusak/vim-dadbod-ui", enabled = false },
	{ "stevearc/oil.nvim", enabled = false },
	{ "tpope/vim-dadbod", enabled = false },
	{ "ThePrimeagen/vim-be-good", enabled = false },
	{ "aadv1k/gdoc.vim", enabled = false },
	{ "echasnovski/mini.ai", enabled = false },
	{ "echasnovski/mini.surround", enabled = false },
	{ "echasnovski/mini.pairs", enabled = false },
	{ "echasnovski/mini.operators", enabled = false },
	{ "echasnovski/mini.bracketed", enabled = false },
	-- { "windwp/nvim-autopairs", enabled = false },
	-- { "tpope/vim-surround", enabled = false },
}
