return {
	"williamboman/mason.nvim",
	cmd = "Mason",
	keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
	build = ":MasonUpdate",
	opts_extend = { "ensure_installed" },
	opts = {
		ensure_installed = {
			"ast-grep",
			"autopep8",
			"black",
			"debugpy",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"flake8",
			"hadolint",
			"harper-ls",
			"isort",
			"jq",
			"lua-language-server",
			"markdown-toc",
			"markdownlint-cli2",
			"marksman",
			"prettierd",
			"pyright",
			"ruff",
			"semgrep",
			"shfmt",
			"sith-language-server",
			"snyk",
			"sonarlint-language-server",
			"sqlfmt",
			"stylua",
			"taplo",
			"terraform-ls",
			"tflint",
			"trivy",
			"vulture",
			"yaml-language-server",
		},
	},
}
