# Set terminal environment and colors
set-option -g default-terminal "${TERM}"
set-option -sg terminal-overrides ',*:RGB'
set-window-option -g xterm-keys on
set-window-option -g automatic-rename off
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'
set-environment -g EDITOR 'nvim'

# Set custom keybinds
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Change windows in the same session
bind-key -n C-S-h swap-window -t -1
bind-key -n C-S-l swap-window -t +1
bind p display-popup -d "#{pane_current_path}" -E -w 80% -h 80% -T scratch

# Set keybinds Vim motions
setw -g mode-keys vi

# Quality of Life settings
set -s escape-time 0 # Set escape-time to 0s
set -g mouse on # Enable adjust pane with mouse
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g detach-on-destroy off
set -g history-limit 1000000
set -g repeat-time 1000

# Visuals - pane borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta
set -g allow-passthrough

# Status settings
set-option -g status-position top
set -g status-interval 5
set -g status-style bg=default,fg=black

# Left status
set -g status-left-length 100
set -g status-left "#[fg=red,nobold] #S | "

# Center status
# set -ga status-left "#[fg=blue,nobold]#[align=absolute-centre] 📅 %a %d %b %Y |#[align=right]"
# set -ga status-left "#[fg=grey]#[align=absolute-centre] 🕰  #[fg=blue,nobold]%H:%M #[align=right]"

# Right status
set -g status-right "#[fg=blue]#{kubectx_cluster}:#[fg=pink]#{kubectx_namespace} "
set -g status-right-length 100

# Bottom pane border
# Source - https://superuser.com/a/1785203
set -g pane-border-status bottom
set -g pane-border-format ' #(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD) #[fg=green]#{pane_current_path} '

# Current window status format
set -g status-justify left
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"
set -g window-status-current-style \
  "fg=pink,bold"
set -g window-status-bell-style \
  "bg=red,nobold"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tony-sol/tmux-kubectx'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
# set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'erikw/tmux-powerline'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'all'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '3'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
