# Set terminal colors
set-option -g default-terminal 'tmux-256color'

# Set Vi mode for copy paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd2Pane

# Unbind default keybindings
unbind c
bind c new-window -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Set new prefix
unbind C-b
set -g prefix ^A

# Renumber windows
set-option -g base-index 1
setw -g pane-base-index 1
setw -g base-index 1
set -g renumber-windows on       # renumber all windows when any window is closed

# General settings
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
set -g mouse on
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.2'

set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# Catppuccin configs
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "yes"

set -g @catppuccin_directory-text "#{pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M:%S"

# # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/.tmux/plugins/tpm/tpm'
