[Interface]
PrivateKey = IXWC7fgm/S+AqxGVfFOZaZZs9uffSqZvQRm81bbl8UI=
Address = 100.89.205.135/32,fd00::19:ce1a/128
MTU = 1280
DNS = 169.254.169.254,1.1.1.1,1.0.0.1

[Peer]
PresharedKey = hEwIvsFeoecQMcoYfEXWDkQ1hH+p6BZQDIG1yBRqdAY=
PublicKey = 4s1aCCjdlKxSA9DBfZnzOTLw0gVHJsLgUUaSW+4mRSQ=
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = vpn.kpayk.com:51820
PersistentKeepalive = 25
